from typing import Final

from centralserver.internals.models.user import DefaultRole

DEFAULT_ROLES: Final[tuple[DefaultRole, ...]] = (
    DefaultRole(id=1, description="Website Administrator", modifiable=False),
    DefaultRole(id=2, description="Superintendent", modifiable=False),
    DefaultRole(id=3, description="Administrator", modifiable=False),
    DefaultRole(id=4, description="Principal", modifiable=False),
    DefaultRole(id=5, description="Canteen Manager", modifiable=False),
)

PERMISSIONS: Final[dict[str, str]] = {
    "notifications:announce": "Create and send announcements to all users.",
    "notifications:global:archive": "Archive notifications owned by any user.",
    "notifications:self:archive": "Archive their own notifications.",
    "notifications:global:view": "View all notifications owned by any user.",
    "notifications:self:view": "View their own notifications.",
    "reports:global:write": "Submit and edit any report in the system.",
    "reports:global:read": "View all reports in the system.",
    "reports:local:write": "Submit and edit monthly reports of their assigned school.",
    "reports:local:read": "View monthly reports of their assigned school.",
    "roles:global:read": "View all user roles.",
    "schools:create": "Create new schools in the system.",
    "schools:global:read": "View all schools in the system.",
    "schools:global:modify": "Modify any school's information.",
    "schools:self:read": "View schools assigned to the user.",
    "schools:self:modify": "Modify their own school's information.",
    "site:manage": "Access and modify the website's settings and configurations.",
    "users:create": "Create new users of any role.",
    "users:global:modify": "Modify any user's information.",
    "users:global:modify:username": "Modify any user's username.",
    "users:global:modify:email": "Modify any user's email address.",
    "users:global:modify:name": "Modify any user's name.",
    "users:global:modify:position": "Modify any user's position/title in the system.",
    "users:global:modify:password": "Modify any user's password.",
    "users:global:modify:avatar": "Modify any user's avatar.",
    "users:global:modify:school": "Modify any user's school association.",
    "users:global:modify:role": "Modify any user's role in the system.",
    "users:global:forceupdate": "Force any user to update their information.",
    "users:global:deactivate": "Deactivate any user account.",
    "users:global:read": "View all users' information.",
    "users:global:simple": "View basic information of all users.",
    "users:self:modify": "Modify their own user information.",
    "users:self:modify:username": "Modify their own username.",
    "users:self:modify:email": "Modify their own email address.",
    "users:self:modify:name": "Modify their own name.",
    "users:self:modify:position": "Modify their own position/title in the system.",
    "users:self:modify:password": "Modify their own password.",
    "users:self:modify:avatar": "Modify their own avatar.",
    "users:self:modify:school": "Modify their own school association.",
    "users:self:modify:role": "Modify their own role in the system.",
    "users:self:forceupdate": "Set their own 'force update' status.",
    "users:self:deactivate": "Deactivate their own user account.",
    "users:self:read": "View their own user information.",
}

ROLE_PERMISSIONS: Final[dict[int, list[str]]] = {
    1: [  # Website Administrator
        "notifications:announce",
        "notifications:global:archive",
        "notifications:self:archive",
        "notifications:global:view",
        "notifications:self:view",
        "schools:global:read",
        "site:manage",
        "users:create",
        "users:global:modify",
        "users:global:modify:username",
        "users:global:modify:email",
        "users:global:modify:name",
        "users:global:modify:password",
        "users:global:modify:position",
        "users:global:modify:avatar",
        "users:global:modify:role",
        "users:global:forceupdate",
        "users:global:deactivate",
        "users:global:read",
        "users:global:simple",
        "users:self:modify",
        "users:self:modify:username",
        "users:self:modify:email",
        "users:self:modify:name",
        "users:self:modify:position",
        "users:self:modify:password",
        "users:self:modify:avatar",
        "users:self:modify:role",
        "users:self:forceupdate",
        "users:self:deactivate",
        "users:self:read",
        "roles:global:read",
    ],
    2: [  # Superintendent
        "notifications:announce",
        "notifications:self:archive",
        "notifications:self:view",
        "reports:global:read",
        "reports:local:write",
        "reports:local:read",
        "schools:create",
        "schools:global:read",
        "schools:global:modify",
        "schools:self:read",
        "schools:self:modify",
        "users:create",
        "users:global:modify",
        "users:global:modify:username",
        "users:global:modify:email",
        "users:global:modify:name",
        "users:global:modify:position",
        "users:global:modify:avatar",
        "users:global:modify:school",
        "users:global:modify:role",
        "users:global:forceupdate",
        "users:global:deactivate",
        "users:global:read",
        "users:global:simple",
        "users:self:modify",
        "users:self:modify:username",
        "users:self:modify:email",
        "users:self:modify:name",
        "users:self:modify:position",
        "users:self:modify:password",
        "users:self:modify:avatar",
        "users:self:modify:school",
        "users:self:modify:role",
        "users:self:forceupdate",
        "users:global:deactivate",
        "users:self:read",
        "roles:global:read",
    ],
    3: [  # Administrator
        "notifications:announce",
        "notifications:self:archive",
        "notifications:self:view",
        "reports:global:read",
        "reports:local:write",
        "reports:local:read",
        "schools:global:read",
        "schools:global:modify",
        "schools:self:read",
        "schools:self:modify",
        "users:global:modify:position",
        "users:global:modify:school",
        "users:global:modify:role",
        "users:global:read",
        "users:global:simple",
        "users:self:modify",
        "users:self:modify:username",
        "users:self:modify:email",
        "users:self:modify:name",
        "users:self:modify:position",
        "users:self:modify:password",
        "users:self:modify:avatar",
        "users:self:modify:school",
        "users:self:modify:role",
        "users:self:forceupdate",
        "users:self:read",
        "roles:global:read",
    ],
    4: [  # Principal
        "notifications:self:archive",
        "notifications:self:view",
        "reports:local:read",
        "reports:local:write",
        "schools:self:read",
        "schools:self:modify",
        "users:self:modify",
        "users:self:modify:email",
        "users:self:modify:password",
        "users:self:modify:avatar",
        "users:self:forceupdate",
        "users:self:read",
        "users:global:simple",
        "roles:global:read",
    ],
    5: [  # Canteen Manager
        "notifications:self:archive",
        "notifications:self:view",
        "reports:local:read",
        "reports:local:write",
        "schools:self:read",
        "users:self:modify",
        "users:self:modify:email",
        "users:self:modify:password",
        "users:self:modify:avatar",
        "users:self:forceupdate",
        "users:self:read",
        "users:global:simple",
        "roles:global:read",
    ],
}
